version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running lint and tests..."
      #- npm run lint # Adjust if you have a different lint command
      #- npm test # Adjust if you have a different test command
      - echo "Waiting for 1 hour to see if we need to refresh the GitHub token..."
      #- sleep 3602 # Wait for 1 hour (commented out)
      - echo "Fetching GitHub token..."
  build:
    commands:
      - echo "Building the app..."
      - npm run build # Adjust this to your actual build command
      - echo "Build completed, checking dist directory..."
      - ls -la dist # This will list the contents of the dist directory

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - 'node_modules/**/*' # Caches node_modules for faster subsequent builds
