version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Running lint and tests..."
      - echo "Running lint and tests..."
      - echo "Waiting for 1 hour to see if we need to refresh the GitHub token..."
      - sleep 3602 # Wait for 1 hour
      - echo "Fetching GitHub token..."
  build:
    commands:
      - echo "Building the app..."
      
      
artifacts:
  files:
    - '**/*'
  base-directory: dist
